### ISSUE TITLE
Add default SearchingContext types to config.

### ISSUE THREAD

**Issue by krzysztof-gzocha** [krzysztof-gzocha/searcher-bundle#20]
Right now developer need to specify a class or a service for his SearchingContext in every context, but in most of the cases the context will be the default one - without any modification.
### Idea

Idea is to add default types of SearchingContext will be resolved to already created services, so the only thing that developer will need to do is specify `context.type` in the config.  
Of course `context.service` will still be there, so developer will always can specify his own (more sophisticated) context.
### Config right now:

``` yaml
k_gzocha_searcher:
  contexts:
    people:
      context:
        service: some_user_specified_service_that_he_needs_to_define
```
### Proposal:

``` yaml
k_gzocha_searcher:
  contexts:
    people:
      context:
        type: doctrine.query_builder # or doctrine.mongo, or elastica
```
