### ISSUE TITLE
Usage of the SearchForm

### ISSUE THREAD

**Issue by aeyoll** [krzysztof-gzocha/searcher-bundle#27]
Hello,
I'm having trouble using the SearchForm class, especially the getPath method for the property_path option, which returns me this error : 

```
PropertyAccessor requires a graph of objects or arrays to operate on, but it found type "NULL" while trying to traverse path "filterModels[specialty].specialty" at property "specialty".
```

Here is my form:

``` php
use KGzocha\Bundle\SearcherBundle\Form\SearchForm as BaseSearchForm;

class SearchForm extends BaseSearchForm
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('specialty', EntityType::class, [
                'class'         => Specialty::class,
                'property_path' => $this->getPath('specialty', 'specialty'),
                'required'      => false
            ]);
    }
}
```

My criteria:

``` php
class SpecialtyCriteria implements CriteriaInterface
{
    private $specialty;
}
```

And my config:

``` yml
k_gzocha_searcher:
    contexts:
        specialty:
            context:
                class: 'KGzocha\Searcher\Context\Doctrine\QueryBuilderSearchingContext'
            criteria:
                - { class: 'Project\Bundle\SpecialtyBundle\Criteria\SpecialtyCriteria', name: specialty}
            builders:
                - { class: 'Project\Bundle\SpecialtyBundle\Criteria\SpecialtyCriteriaBuilder', name: specialty }
```

Thanks a lot!
Jean-Philippe
