### ISSUE TITLE
Usage of the context service

### ISSUE THREAD

**Issue by aeyoll** [krzysztof-gzocha/searcher-bundle#31]
Hello!
I'm aving trouble using the "searching_context_service" part of the documentation. I tried to define a service to get a query builder, but I got this error when submitting a form :

```
InvalidDefinitionException in SearchingContext.php line 72:
Service "doctor_searching_context" configured for context insearching context "doctor" does not exist
```

Here is my configuration, with the services:

``` yml
k_gzocha_searcher:
    contexts:
        doctor:
            context:
                # class: 'KGzocha\Searcher\Context\Doctrine\QueryBuilderSearchingContext'
                service: doctor_searching_context
            criteria:
                - { class: 'DocTooMe\Bundle\SpecialtyBundle\Criteria\SpecialtyCriteria', name: specialty}
            builders:
                - { class: 'DocTooMe\Bundle\SpecialtyBundle\Criteria\SpecialtyCriteriaBuilder', name: specialty }
```

In my bundle services.yml :

``` yml
services:
    project_doctor.query_builder:
        class: Project\Bundle\DoctorBundle\Entity\DoctorRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: createQueryBuilder

    project_doctor.searching_context:
        class: KGzocha\Searcher\Context\QueryBuilderSearchingContext
        arguments:
            - @project_doctor.query_builder

    doctor_searching_context:
        alias: project_doctor.searching_context
```

Thanks a lot,
Jean-Philippe

**Comment by krzysztof-gzocha** [comment]
Line 72 in SearchingContext.php is:

``` php
if (!$container->hasDefinition($config['service'])) {
```

so it's checking if container has proper service, before using it.

There is unit test that is checking this `\KGzocha\Bundle\SearcherBundle\Test\DependencyInjection\ServiceDefiner\SearchingContextTest::testCollectionDefinedWithService` and it is working fine, so are you sure your service is accessible? Could you confirm that you have access to `doctor_searching_context` and/or `project_doctor.searching_context` from other places?

**Comment by aeyoll** [comment]
If I comment the context service configuration:

``` yml
            context:
                class: 'KGzocha\Searcher\Context\Doctrine\QueryBuilderSearchingContext'
                # service: doctor_searching_context
```

and I debug the container, I can see the services correctly:

```
$ php app/console debug:container project_doctor.searching_context

Information for Service "project_doctor.searching_context"
=============================================================

 ------------------ -------------------------------------------------------
  Option             Value
 ------------------ -------------------------------------------------------
  Service ID         project_doctor.searching_context
  Class              KGzocha\Searcher\Context\QueryBuilderSearchingContext
  Tags               -
  Scope              container
  Public             yes
  Synthetic          no
  Lazy               no
  Synchronized       no
  Abstract           no
  Autowired          no
  Autowiring Types   -
 ------------------ -------------------------------------------------------
```

```
 $ php app/console debug:container doctor_searching_context

 // This service is an alias for the service project_doctor.searching_context
```

**Comment by krzysztof-gzocha** [comment]
I'm guessing that setting `project_doctor.searching_context` in the config did not helped?
If not then I'm guessing that bundle is trying to access the service before your service is created, but I would need to test it

**Comment by aeyoll** [comment]
If it can help, here is the full stack strace:

```
InvalidDefinitionException in SearchingContext.php line 72:
Service "doctor_searching_context" configured for context insearching context "doctor" does not exist

in SearchingContext.php line 72
at SearchingContext::checkServiceExists(object(ContainerBuilder), 'doctor', array('service' => 'doctor_searching_context', 'class' => null)) in SearchingContext.php line 31
at SearchingContext::defineServices('doctor', array('context' => array('service' => 'doctor_searching_context', 'class' => null), 'criteria' => array(array('class' => 'Project\Bundle\SpecialtyBundle\Criteria\SpecialtyCriteria', 'name' => 'specialty', 'service' => null)), 'builders' => array(array('class' => 'Project\Bundle\SpecialtyBundle\Criteria\SpecialtyCriteriaBuilder', 'name' => 'specialty', 'service' => null)), 'criteria_collection' => array('class' => 'KGzocha\Searcher\Criteria\Collection\NamedCriteriaCollection', 'service' => null), 'builder_collection' => array('class' => 'KGzocha\Searcher\CriteriaBuilder\Collection\CriteriaBuilderCollection', 'service' => null), 'searcher' => array('class' => 'KGzocha\Searcher\Searcher', 'service' => null, 'wrapper_class' => 'KGzocha\Searcher\WrappedResultsSearcher')), object(ContainerBuilder)) in KGzochaSearcherExtension.php line 57
at KGzochaSearcherExtension->defineContexts(array('contexts' => array('doctor' => array('context' => array('service' => 'doctor_searching_context', 'class' => null), 'criteria' => array(array('class' => 'Project\Bundle\SpecialtyBundle\Criteria\SpecialtyCriteria', 'name' => 'specialty', 'service' => null)), 'builders' => array(array('class' => 'Project\Bundle\SpecialtyBundle\Criteria\SpecialtyCriteriaBuilder', 'name' => 'specialty', 'service' => null)), 'criteria_collection' => array('class' => 'KGzocha\Searcher\Criteria\Collection\NamedCriteriaCollection', 'service' => null), 'builder_collection' => array('class' => 'KGzocha\Searcher\CriteriaBuilder\Collection\CriteriaBuilderCollection', 'service' => null), 'searcher' => array('class' => 'KGzocha\Searcher\Searcher', 'service' => null, 'wrapper_class' => 'KGzocha\Searcher\WrappedResultsSearcher')))), object(ContainerBuilder)) in KGzochaSearcherExtension.php line 35
at KGzochaSearcherExtension->load(array(array('contexts' => array('doctor' => array('context' => array('service' => 'doctor_searching_context'), 'criteria' => array(array('class' => 'Project\Bundle\SpecialtyBundle\Criteria\SpecialtyCriteria', 'name' => 'specialty')), 'builders' => array(array('class' => 'Project\Bundle\SpecialtyBundle\Criteria\SpecialtyCriteriaBuilder', 'name' => 'specialty')))))), object(ContainerBuilder)) in MergeExtensionConfigurationPass.php line 55
at MergeExtensionConfigurationPass->process(object(ContainerBuilder)) in MergeExtensionConfigurationPass.php line 39
at MergeExtensionConfigurationPass->process(object(ContainerBuilder)) in Compiler.php line 104
at Compiler->compile(object(ContainerBuilder)) in ContainerBuilder.php line 597
at ContainerBuilder->compile() in bootstrap.php.cache line 2707
at Kernel->initializeContainer() in bootstrap.php.cache line 2485
at Kernel->boot() in bootstrap.php.cache line 2516
at Kernel->handle(object(Request)) in app.php line 53
```

**Comment by krzysztof-gzocha** [comment]
Did you tried to configure it with service `project_doctor.searching_context`?

Edit: I've tried it and it didn't worked. I need to investigate it further..

**Comment by krzysztof-gzocha** [comment]
I've manage to fix the issue with this code:

``` php
class KGzochaSearcherExtension extends Extension implements CompilerPassInterface
{
    /**
     * @var array
     */
    private $config;

    /**
     * @inheritDoc
     */
    public function load(array $configs, ContainerBuilder $container)
    {
        $config = $this->processConfiguration(new Configuration(), $configs);
        $loader = new YamlFileLoader(
            $container,
            new FileLocator(__DIR__.'/../Resources/config')
        );

        $loader->load('services.yml');
        $this->config = $config;
    }

    public function process(ContainerBuilder $container)
    {
        $this->defineContexts($this->config, $container);
    }
// rest of the class
```

will need to test it further, but I will do it tomorrow

**Comment by krzysztof-gzocha** [comment]
@aeyoll PR #32 should fix your problem. Can you update composer.json to use `krzysztof-gzocha/composer` to double check if it works for you?

**Comment by aeyoll** [comment]
@krzysztof-gzocha Can you rebase the "composer" branch with master? It's missing the #30 PR, so I can't test. Thanks!

**Comment by krzysztof-gzocha** [comment]
@aeyoll rebased, you can try now

**Comment by aeyoll** [comment]
@krzysztof-gzocha   Thanks, it seems to solve the issue of the unfound service. However, can you show me an example on how you set up your searching_context service please? Thanks.

**Comment by krzysztof-gzocha** [comment]
Thanks for reply.
Sure I can!
config.yaml:

``` yaml
k_gzocha_searcher:
  contexts:
    people:
      context:
        service: project_doctor.searching_context

      criteria:
        - { class: 'KGzocha\Searcher\Criteria\TextCriteria', name: criteria1 }

      builders:
        - { class: 'AppBundle\CriteriaBuilder', name: builder1 }
```

services.yml

``` yaml
services:
  project_doctor.searching_context:
      class: 'AppBundle\Context'

  doctor_searching_context:
      alias: project_doctor.searching_context
```

and in composer.json:

``` json
"require": {
  "php": ">=5.5.9",
  "symfony/symfony": "3.1.*",
  ..
}
```

I will merge the PR and tag the version

**Comment by krzysztof-gzocha** [comment]
@aeyoll you can now use version `3.0.2`

**Comment by aeyoll** [comment]
@krzysztof-gzocha Thanks! And what's your `AppBundle\Context` class looking like? If I understand correctly, it needs to have a queryBuilder in it's constructor, right?

**Comment by krzysztof-gzocha** [comment]
It's just some dummy object, without any params, just to prove searcher is working with contexts declared as services. It just implements proper interface, but methods are empty.

It doesn't need to be constructed with some query builder.
For example SearchingContext that would use Finder as query builder does not need any param, because you can create Finder instance on your own in the constructor (its not the best approach, but it is possible).

Look [here](http://searcher.readthedocs.io/en/latest/complete-example.html) or [here](http://searcher.readthedocs.io/en/latest/class/searching-context.html) for some examples

**Comment by aeyoll** [comment]
@krzysztof-gzocha I mean, do you have an example of a concreate working implementation of the Context? I must say that this is a little blurry in the documentation :smile:

**Comment by krzysztof-gzocha** [comment]
It is hard for me to create easy to understand, clear documentation for such generic class as SearchingContext. If you will have any better doc or example - fill free to send PR to searcher library with fixes to the docs ;)

Either way I will give you example service declaration for SearchingContext that will use Doctrine's ORM for some dummy entity. I will try to do it today

**Comment by krzysztof-gzocha** [comment]
Well I can't do it today, so I will give you some working example of `FinderSearchingContext`.

config.yml

``` yaml

k_gzocha_searcher:
  contexts:
    people:
      context:
        service: project_doctor.searching_context

      criteria:
        - { class: 'KGzocha\Searcher\Criteria\TextCriteria', name: criteria1 }

      builders:
        - { class: 'AppBundle\CriteriaBuilder', name: builder1 }
```

services.yml:

``` yaml
services:
  project_doctor.finder:
    class: 'Symfony\Component\Finder\Finder'

  project_doctor.searching_context:
      class: 'KGzocha\Searcher\Context\FinderSearchingContext'
      arguments:
        - '@project_doctor.finder'
```

---

For Doctrine's ORM you would need to get proper QueryBuilder first (instead of Finder in above example), for example in this way (should work, but I was writing this mostly from memory):

``` yaml
services:
  project_doctor.query_builder:
      class: Doctrine\ORM\QueryBuilder
      factory: ['@entity.repository', 'createQueryBuilder']
      arguments:
        - 'alias'
```

then you can inject this into `\KGzocha\Searcher\Context\Doctrine\QueryBuilderSearchingContext` like this:

``` yaml
project_doctor.searching_context:
      class: 'KGzocha\Searcher\Context\Doctrine\QueryBuilderSearchingContext'
      arguments:
        - '@project_doctor.query_builder'
```

and this should work just fine, of course change `@entity.repository` and `alias` to better values :)
